// -*- Mode: idl; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*-
//
// Copyright (C) 2013 Opera Software ASA.  All rights reserved.
//
// This file is an original work developed by Opera Software ASA

// Required by Opera's log-in flow for Sync
namespace syncPrivate {
  interface Functions {
    // Sets log-in information required by Sync to make requests to the Sync
    // server.
    static void loginSuccess(DOMString authToken,
                             DOMString authTokenSecret,
                             DOMString userID,
                             DOMString userName,
                             DOMString accountUserName,
                             DOMString accountFullUserName);

    // Informs Sync about failure to obtain log-in information.
    static void loginFailure(DOMString error);
  };
};
